import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

const attractions = {
  'hoan-kiem-lake': { name: 'Hoan Kiem Lake', city: 'Hanoi', type: 'FREE CITY LANDMARK', intro: 'Hoan Kiem Lake is Hanoi’s easiest first walk: a central meeting point for morning exercise, Old Quarter food and an evening change of pace.', best: 'Best for first-time visitors, photographers and travelers with a short Hanoi stop.', time: 'Allow 45–90 minutes, longer if you combine it with the Old Quarter.', ticket: 'The lake and public walking areas are free. Nearby museums, temples or shows may have separate entry rules.', how: 'Walk from the Old Quarter or French Quarter. Go early for cooler air, or around sunset for atmosphere. Check current restrictions before special events.', nearby: [{ href: '/en/hanoi', label: 'Hanoi travel guide' }, { href: '/en/attractions/hanoi-old-quarter', label: 'Hanoi Old Quarter guide' }], faq: 'Do I need a ticket for Hoan Kiem Lake? No for the public lake area; treat nearby attractions separately.' },
  'ho-chi-minh-mausoleum': { name: 'Ho Chi Minh Mausoleum', city: 'Hanoi', type: 'PRACTICAL VISIT GUIDE', intro: 'The Ho Chi Minh Mausoleum complex is a significant Hanoi visit where timing, dress and official access rules matter more than rushing through a checklist.', best: 'Best for travelers interested in modern Vietnamese history and formal civic landmarks.', time: 'Allow 1–2 hours for the complex and nearby sites, with extra time for queues or access controls.', ticket: 'Do not rely on a generic ticket claim. Check the official visitor guidance, opening days, dress requirements and security rules before going.', how: 'Plan this as a morning visit and confirm the current access schedule first. Wear respectful clothing and carry only what the security rules allow.', nearby: [{ href: '/en/hanoi', label: 'Hanoi travel guide' }, { href: '/en/vietnam-itinerary-7-days', label: '7-day Vietnam itinerary' }], faq: 'Can I visit any day? Access and opening arrangements can change, so verify official guidance on the day you plan to visit.' },
  'temple-of-literature-hanoi': { name: 'Temple of Literature', city: 'Hanoi', type: 'CULTURE & HISTORY', intro: 'The Temple of Literature is one of Hanoi’s most rewarding compact cultural visits, especially when you want history without a full-day excursion.', best: 'Best for history, architecture, photography and a calm break from Old Quarter traffic.', time: 'Allow 60–90 minutes.', ticket: 'This is a ticketed cultural site. Check the current official admission price and opening information before visiting.', how: 'Pair it with the Mausoleum area or a Hanoi food route. Visit earlier in the day for softer light and a more comfortable walk.', nearby: [{ href: '/en/hanoi', label: 'Hanoi travel guide' }, { href: '/en/attractions/ho-chi-minh-mausoleum', label: 'Mausoleum visit guide' }], faq: 'Is it worth visiting on a short trip? Yes, because its compact layout fits neatly into a half-day Hanoi plan.' },
  'my-khe-beach': { name: 'My Khe Beach', city: 'Da Nang', type: 'BEACH & DOWNTIME', intro: 'My Khe Beach is Da Nang’s simplest reset: an easy public coastline that works before breakfast, after sightseeing or as the anchor for a slower central Vietnam stay.', best: 'Best for beach time, families, couples and travelers who want a low-friction city/coast combination.', time: 'Allow 1–3 hours; reserve a half-day if you want a relaxed swim and meal nearby.', ticket: 'The public beach is free. Chair rental, food, water activities and private facilities can cost extra; check locally.', how: 'Stay near the coast for easy access, check sea conditions and use the beach as a flexible slot rather than a rigid timed attraction.', nearby: [{ href: '/en/da-nang-hoi-an', label: 'Da Nang & Hoi An guide' }, { href: '/en/attractions/marble-mountains-da-nang', label: 'Marble Mountains guide' }], faq: 'Is My Khe Beach good for a short Da Nang stay? Yes; it is one of the easiest attractions to add without a long transfer.' },
  'marble-mountains-da-nang': { name: 'Marble Mountains', city: 'Da Nang', type: 'NATURE & CULTURE', intro: 'Marble Mountains combines caves, pagodas, viewpoints and a short escape from Da Nang’s beach strip, but stairs and heat should shape your timing.', best: 'Best for active travelers, temples, viewpoints and a half-day from Da Nang or Hoi An.', time: 'Allow 2–3 hours including stairs and photo stops.', ticket: 'Some areas require admission or lift choices. Check the current official ticket and access information before setting out.', how: 'Go early, wear shoes with grip and carry water. Combine it with My Khe Beach or continue toward Hoi An only if traffic and energy allow.', nearby: [{ href: '/en/da-nang-hoi-an', label: 'Da Nang & Hoi An guide' }, { href: '/en/attractions/my-khe-beach', label: 'My Khe Beach guide' }], faq: 'Is Marble Mountains difficult? The visit includes stairs and uneven surfaces; choose a shorter route if heat or mobility is a concern.' },
} as const;

export function generateStaticParams() { return Object.keys(attractions).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const a = attractions[slug as keyof typeof attractions]; return a ? { title: `${a.name} ${a.city} Guide`, description: a.intro, alternates: { canonical: `/en/attractions/${slug}` } } : {}; }
export default async function AttractionPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const a = attractions[slug as keyof typeof attractions]; if (!a) notFound(); return <main className="attractionPage shell"><a className="brand" href="/">VietnamGo<span>.</span></a><p className="kicker">{a.type} · {a.city}</p><h1>{a.name}: visitor guide</h1><p className="attractionIntro">{a.intro}</p><section className="attractionGrid"><div><h2>Why visit and who is it for?</h2><p>{a.best}</p><h2>How much time do you need?</h2><p>{a.time}</p><h2>Tickets and booking</h2><p>{a.ticket}</p><h2>How to visit</h2><p>{a.how}</p></div><aside><strong>Before you go</strong><p>Check current official information for opening hours, access rules and ticket availability. VietnamGo does not invent live prices.</p><a className="primary" href={`/en/planner?days=10&arrival=${encodeURIComponent(a.city)}&style=couple&budget=mid&interest=${a.city === 'Da Nang' ? 'beach' : 'food'}`}>Build this into my trip →</a><small>Some booking links may be affiliate links.</small></aside></section><section className="attractionFaq"><h2>FAQ</h2><p>{a.faq}</p></section><section className="attractionRelated"><h2>Plan around this attraction</h2>{a.nearby.map((x) => <a className="secondary" href={x.href} key={x.href}>{x.label} →</a>)}</section></main>; }
